package com.keziko.dvdtek.enums;

import java.util.HashMap;
import java.util.Map;

/*
 * Nom de classe : CodePaysEnum
 * Description   :
 * Version       : 1.0
 * Date          : 15/03/2020
 * Copyright     : Luc CLÉMENT - lucclement38@gmail.com
 */
public enum CodePaysEnum {

    AF("AF", "Afghanistan"),
    AX("AX", "Îles Åland"),
    AL("AL", "Albanie"),
    DZ("DZ", "Algérie"),
    AS("AS", "Samoa américaines"),
    AD("AD", "Andorre"),
    AO("AO", "Angola"),
    AI("AI", "Anguilla"),
    AQ("AQ", "Antarctique"),
    AG("AG", "Antigua-et-Barbuda"),
    AR("AR", "Argentine"),
    AM("AM", "Arménie"),
    AW("AW", "Aruba"),
    AU("AU", "Australie"),
    AT("AT", "Autriche"),
    AZ("AZ", "Azerbaïdjan"),
    BS("BS", "Bahamas"),
    BH("BH", "Bahreïn"),
    BD("BD", "Bangladesh"),
    BB("BB", "Barbade"),
    BY("BY", "Biélorussie"),
    BE("BE", "Belgique"),
    BZ("BZ", "Belize"),
    BJ("BJ", "Bénin"),
    BM("BM", "Bermudes"),
    BT("BT", "Bhoutan"),
    BO("BO", "Bolivie"),
    BA("BA", "Bosnie-Herzégovine"),
    BW("BW", "Botswana"),
    BV("BV", "Île Bouvet"),
    BR("BR", "Brésil"),
    VG("VG", "British Virgin Islands"),
    IO("IO", "Territoire britannique de l’Océan Indien"),
    BN("BN", "Brunei Darussalam"),
    BG("BG", "Bulgarie"),
    BF("BF", "Burkina Faso"),
    BI("BI", "Burundi"),
    KH("KH", "Cambodge"),
    CM("CM", "Cameroun"),
    CA("CA", "Canada"),
    CV("CV", "Cap-Vert"),
    KY("KY", "Iles Cayman"),
    CF("CF", "République centrafricaine"),
    TD("TD", "Tchad"),
    CL("CL", "Chili"),
    CN("CN", "Chine"),
    HK("HK", "Hong Kong"),
    MO("MO", "Macao"),
    CX("CX", "Île Christmas"),
    CC("CC", "Îles Cocos"),
    CO("CO", "Colombie"),
    KM("KM", "Comores"),
    CG("CG", "République du Congo"),
    CD("CD", "République démocratique du Congo"),
    CK("CK", "Îles Cook"),
    CR("CR", "Costa Rica"),
    CI("CI", "Côte d’Ivoire"),
    HR("HR", "Croatie"),
    CU("CU", "Cuba"),
    CY("CY", "Chypre"),
    CZ("CZ", "République tchèque"),
    DK("DK", "Danemark"),
    DJ("DJ", "Djibouti"),
    DM("DM", "Dominique"),
    DO("DO", "République dominicaine"),
    EC("EC", "Équateur"),
    EG("EG", "Égypte"),
    SV("SV", "Salvador"),
    GQ("GQ", "Guinée équatoriale"),
    ER("ER", "Érythrée"),
    EE("EE", "Estonie"),
    ET("ET", "Éthiopie"),
    FK("FK", "Îles Falkland"),
    FO("FO", "Îles Féroé"),
    FJ("FJ", "Fidji"),
    FI("FI", "Finlande"),
    FR("FR", "France"),
    GF("GF", "Guyane française"),
    PF("PF", "Polynésie française"),
    TF("TF", "Terres australes et antarctiques françaises"),
    GA("GA", "Gabon"),
    GM("GM", "Gambie"),
    GE("GE", "Géorgie"),
    DE("DE", "Allemagne"),
    GH("GH", "Ghana"),
    GI("GI", "Gibraltar"),
    GR("GR", "Grèce"),
    GL("GL", "Groenland"),
    GD("GD", "Grenade"),
    GP("GP", "Guadeloupe"),
    GU("GU", "Guam"),
    GT("GT", "Guatemala"),
    GG("GG", "Guernesey"),
    GN("GN", "Guinée"),
    GW("GW", "Guinée-Bissau"),
    GY("GY", "Guyane"),
    HT("HT", "Haïti"),
    HM("HM", "Îles Heard-et-MacDonald"),
    VA("VA", "Saint-Siège (Vatican)"),
    HN("HN", "Honduras"),
    HU("HU", "Hongrie"),
    IS("IS", "Islande"),
    IN("IN", "Inde"),
    ID("ID", "Indonésie"),
    IR("IR", "Iran"),
    IQ("IQ", "Irak"),
    IE("IE", "Irlande"),
    IM("IM", "Ile de Man"),
    IL("IL", "Israël"),
    IT("IT", "Italie"),
    JM("JM", "Jamaïque"),
    JP("JP", "Japon"),
    JE("JE", "Jersey"),
    JO("JO", "Jordanie"),
    KZ("KZ", "Kazakhstan"),
    KE("KE", "Kenya"),
    KI("KI", "Kiribati"),
    KP("KP", "Corée du Nord"),
    KR("KR", "Corée du Sud"),
    KW("KW", "Koweït"),
    KG("KG", "Kirghizistan"),
    LA("LA", "Laos"),
    LV("LV", "Lettonie"),
    LB("LB", "Liban"),
    LS("LS", "Lesotho"),
    LR("LR", "Libéria"),
    LY("LY", "Libye"),
    LI("LI", "Liechtenstein"),
    LT("LT", "Lituanie"),
    LU("LU", "Luxembourg"),
    MK("MK", "Macédoine"),
    MG("MG", "Madagascar"),
    MW("MW", "Malawi"),
    MY("MY", "Malaisie"),
    MV("MV", "Maldives"),
    ML("ML", "Mali"),
    MT("MT", "Malte"),
    MH("MH", "Îles Marshall"),
    MQ("MQ", "Martinique"),
    MR("MR", "Mauritanie"),
    MU("MU", "Maurice"),
    YT("YT", "Mayotte"),
    MX("MX", "Mexique"),
    FM("FM", "Micronésie"),
    MD("MD", "Moldavie"),
    MC("MC", "Monaco"),
    MN("MN", "Mongolie"),
    ME("ME", "Monténégro"),
    MS("MS", "Montserrat"),
    MA("MA", "Maroc"),
    MZ("MZ", "Mozambique"),
    MM("MM", "Myanmar"),
    NA("NA", "Namibie"),
    NR("NR", "Nauru"),
    NP("NP", "Népal"),
    NL("NL", "Pays-Bas"),
    NC("NC", "Nouvelle-Calédonie"),
    NZ("NZ", "Nouvelle-Zélande"),
    NI("NI", "Nicaragua"),
    NE("NE", "Niger"),
    NG("NG", "Nigeria"),
    NU("NU", "Niue"),
    NF("NF", "Île Norfolk"),
    MP("MP", "Îles Mariannes du Nord"),
    NO("NO", "Norvège"),
    OM("OM", "Oman"),
    PK("PK", "Pakistan"),
    PW("PW", "Palau"),
    PS("PS", "Palestine"),
    PA("PA", "Panama"),
    PG("PG", "Papouasie-Nouvelle-Guinée"),
    PY("PY", "Paraguay"),
    PE("PE", "Pérou"),
    PH("PH", "Philippines"),
    PN("PN", "Pitcairn"),
    PL("PL", "Pologne"),
    PT("PT", "Portugal"),
    PR("PR", "Puerto Rico"),
    QA("QA", "Qatar"),
    RE("RE", "Réunion"),
    RO("RO", "Roumanie"),
    RU("RU", "Russie"),
    RW("RW", "Rwanda"),
    BL("BL", "Saint-Barthélemy"),
    SH("SH", "Sainte-Hélène"),
    KN("KN", "Saint-Kitts-et-Nevis"),
    LC("LC", "Sainte-Lucie"),
    MF("MF", "Saint-Martin (partie française)"),
    SX("SX", "Saint-Martin (partie néerlandaise)"),
    PM("PM", "Saint-Pierre-et-Miquelon"),
    VC("VC", "Saint-Vincent-et-les Grenadines"),
    WS("WS", "Samoa"),
    SM("SM", "Saint-Marin"),
    ST("ST", "Sao Tomé-et-Principe"),
    SA("SA", "Arabie Saoudite"),
    SN("SN", "Sénégal"),
    RS("RS", "Serbie"),
    SC("SC", "Seychelles"),
    SL("SL", "Sierra Leone"),
    SG("SG", "Singapour"),
    SK("SK", "Slovaquie"),
    SI("SI", "Slovénie"),
    SB("SB", "Îles Salomon"),
    SO("SO", "Somalie"),
    ZA("ZA", "Afrique du Sud"),
    GS("GS", "Géorgie du Sud et les îles Sandwich du Sud"),
    SS("SS", "Sud-Soudan"),
    ES("ES", "Espagne"),
    LK("LK", "Sri Lanka"),
    SD("SD", "Soudan"),
    SR("SR", "Suriname"),
    SJ("SJ", "Svalbard et Jan Mayen"),
    SZ("SZ", "Eswatini"),
    SE("SE", "Suède"),
    CH("CH", "Suisse"),
    SY("SY", "Syrie"),
    TW("TW", "Taiwan"),
    TJ("TJ", "Tadjikistan"),
    TZ("TZ", "Tanzanie"),
    TH("TH", "Thaïlande"),
    TL("TL", "Timor-Leste"),
    TG("TG", "Togo"),
    TK("TK", "Tokelau"),
    TO("TO", "Tonga"),
    TT("TT", "Trinité-et-Tobago"),
    TN("TN", "Tunisie"),
    TR("TR", "Turquie"),
    TM("TM", "Turkménistan"),
    TC("TC", "Îles Turques-et-Caïques"),
    TV("TV", "Tuvalu"),
    UG("UG", "Ouganda"),
    UA("UA", "Ukraine"),
    AE("AE", "Émirats Arabes Unis"),
    GB("GB", "Royaume-Uni"),
    UK("UK", "Royaume-Uni"),
    US("US", "États-Unis"),
    UM("UM", "Îles mineures éloignées des États-Unis"),
    UY("UY", "Uruguay"),
    UZ("UZ", "Ouzbékistan"),
    VU("VU", "Vanuatu"),
    VE("VE", "Venezuela"),
    VN("VN", "Viêt Nam"),
    VI("VI", "Îles Vierges américaines"),
    WF("WF", "Wallis-et-Futuna"),
    EH("EH", "Sahara occidental"),
    YE("YE", "Yémen"),
    ZM("ZM", "Zambie"),
    ZW("ZW", "Zimbabwe");


    private static final Map<String, CodePaysEnum> BY_CODE = new HashMap<>();
    private static final Map<String, CodePaysEnum> BY_LABEL = new HashMap<>();
    static {
        for (CodePaysEnum e : values()) {
            BY_CODE.put(e.code, e);
            BY_LABEL.put(e.label,e);
        }
    }
    public final String code;
    public final String label;

    private CodePaysEnum(String code, String label){
        this.code = code;
        this.label = label;
    }

    public static CodePaysEnum valueOfCode(String code){
        return BY_CODE.get(code);
    }
    private static CodePaysEnum valueOfLabel(String label){
        return BY_LABEL.get(label);
    }
}
